name: Delete Failed Runs
on: [push]
jobs:
  delete:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Delete Failed Runs
        run: |
          gh run list --limit 100 --json databaseId,conclusion -q '.[] | select(.conclusion == "failure") | .databaseId' > failed_runs.txt
          while read run; do
            gh run delete "$run" || true
          done < failed_runs.txt
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
